VERSION := 5.3
BUILDARG_VERSION := --build-arg VERSION=$(VERSION)
IMAGENAME := docker.io/silviof/docker-languagetool

envout:
	@echo "VERSION=$(VERSION)"
	@echo "BUILDARG_VERSION=$(BUILDARG_VERSION)"
	@echo "IMAGENAME=$(IMAGENAME)"
